templates:
  - "templates/redis.template.yml"
  - "templates/web.template.yml"
  - "templates/web.ratelimited.template.yml"

expose:
  - "80:80"

# any extra arguments for Docker?
# docker_args:

params:
  ## Which Git revision should this container use? (default: tests-passed)
  version: tests-passed

env:
  LANG: en_US.UTF-8
  CHAMBER_VERSION: v1.13.0
  DISCOURSE_HOSTNAME:
  DISCOURSE_SMTP_ADDRESS:

hooks:
  before_bundle_exec:
    - exec:
        cd: $home/lib/tasks
        cmd:
          - "echo 'Rake::Task[\"db:migrate\"].clear; task \"db:migrate\"; # killme' >> db.rake"
          - "echo 'Rake::Task[\"assets:precompile\"].clear; task \"assets:precompile\"; # killme' >> assets.rake"
  after_bundle_exec:
    - replace:
        filename: /var/www/discourse/lib/tasks/db.rake
        from: /Rake::Task.*killme$/
        to: ""
    - replace:
        filename: /var/www/discourse/lib/tasks/assets.rake
        from: /Rake::Task.*killme$/
        to: ""


## Remember, this is YAML syntax - you can only have one block with a name
run:
  - exec: echo "Beginning of custom commands"
  - exec: curl --silent --location https://github.com/segmentio/chamber/releases/download/${CHAMBER_VERSION}/chamber-${CHAMBER_VERSION}-linux-amd64 -o /usr/local/bin/chamber
  - file:
      path: /sbin/eb-boot
      chmod: "+x"
      contents: |
        #!/bin/bash -ex
        # we need redis to migrate.
        echo Starting Redis
        chpst -u redis -U redis /usr/bin/redis-server /etc/redis/redis.conf --daemonize yes

        (
          cd /var/www/discourse
          echo rake db:migrate
          su discourse -c 'bundle exec rake db:migrate'
          echo rake assets:precompile
          su discourse -c 'bundle exec rake assets:precompile'
        )

        echo Shutting down Redis
        redis-cli shutdown

        echo Booting
        chamber $DISCOURSE_ENV exec -- /sbin/boot

  - exec: echo "End of custom commands"
