templates:
  - "templates/redis.template.yml"
  - "templates/web.template.yml"
  - "templates/web.ratelimited.template.yml"

expose:
  - "80:80"

# any extra arguments for Docker?
# docker_args:

params:
  ## Which Git revision should this container use? (default: tests-passed)
  version: tests-passed

env:
  LANG: en_US.UTF-8
  DISCOURSE_HOSTNAME:
  DISCOURSE_SMTP_ADDRESS:

hooks:
  before_bundle_exec:
    - exec:
        cd: $home/lib/tasks
        cmd:
          - "echo 'Rake::Task[\"db:migrate\"].clear; task \"db:migrate\"; # killme' >> db.rake"
          - "echo 'Rake::Task[\"assets:precompile\"].clear; task \"assets:precompile\"; # killme' >> assets.rake"
  after_bundle_exec:
    - replace:
        filename: /var/www/discourse/lib/tasks/db.rake
        from: /Rake::Task.*killme$/
        to: ""
    - replace:
        filename: /var/www/discourse/lib/tasks/assets.rake
        from: /Rake::Task.*killme$/
        to: ""


## Remember, this is YAML syntax - you can only have one block with a name
run:
  - exec: echo "Beginning of custom commands"
  - exec: apt-get install python3-setuptools python3-dev -y
  - exec: easy_install3 pip
  - exec: pip3 install credstash
  - file:
      path: /sbin/eb-boot
      chmod: "+x"
      contents: |
        #!/bin/bash -ex
        env

        echo Getting credentials
        export DISCOURSE_DB_PASSWORD=$(credstash get discourse_db_password env=$DISCOURSE_ENV)
        export DISCOURSE_SMTP_PASSWORD=$(credstash get discourse_smtp_password env=$DISCOURSE_ENV)

        # we need redis to migrate.
        echo Starting Redis
        chpst -u redis -U redis /usr/bin/redis-server /etc/redis/redis.conf --daemonize yes

        (
          cd /var/www/discourse
          echo rake db:migrate
          su discourse -c 'bundle exec rake db:migrate'
          echo rake assets:precompile
          su discourse -c 'bundle exec rake assets:precompile'
        )

        echo Shutting down Redis
        redis-cli shutdown

        echo Booting
        exec /sbin/boot

  - exec: echo "End of custom commands"
